services:
  - type: web
    name: chatgpt2api-register
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    envVars:
      - key: PROXY_SUB_URL
        value: https://random-argo-production.up.railway.app/r9x2m7k4
      - key: STORAGE_BACKEND
        value: postgres
      - key: DATABASE_URL
        value: postgresql://gpt:REDACTED_DB_PASSWORD@gpt520-17269.jxf.gcp-us-west2.cockroachlabs.cloud:26257/defaultdb?sslmode=require
      - key: CHATGPT2API_AUTH_KEY
        sync: false
      - key: LOG_LEVEL
        value: warning
